vich_uploader:
    db_driver: orm # or mongodb or phpcr

    mappings:
        client_image:
            uri_prefix: /images/clients
            upload_destination: '%kernel.project_dir%/public/images/clients'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'